name = "AffineArithmetic"
uuid = "2e89c364-fad6-56cb-99bd-ebadcd2cf8d2"
authors = ["dpsanders"]
version = "0.1.0"

[deps]
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
IntervalArithmetic = "≥ 0.15.0"
julia = "≥ 1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"

[targets]
test = ["Test", "Polynomials"]
